export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_MONSTERS_PENDING = 'REQUEST_MONSTERS_PENDING';
export const REQUEST_MONSTERS_SUCCESS = 'REQUEST_MONSTERS_SUCCESS';
export const REQUEST_MONSTERS_FAILED = 'REQUEST_MONSTERS_FAILED';